resolver: lts-13.1

packages:
- location: lib/todo-backend
- location: lib/todo-backend-added
- location: lib/todo-backend-removed

- location: examples/protocols
- location: examples/versioning

extra-deps:

# thrift-0.11.0 is not yet published to Hackage
# and we need to build it from source (github)
- git: git@github.com:apache/thrift
  commit: fc0ff81
  subdirs:
    - lib/hs

allow-newer: true
